### ISSUE TITLE
How to install and use in neovim?

### ISSUE THREAD

**Issue by TATOAO** [urxvtcd/vim-indent-object#1]
Hi, 

Sorry, I am a noob, I try to install it using Packer in neovim:

use 'urxvtcd/vim-indent-object'

and the installation was completed, but it doesn't seem working. Maybe I need to change some config, may I know how?

**Comment by urxvtcd** [comment]
By default there are no mappings, for example I use these keybinds for linewise mappings:
```vim
omap ii <Plug>(indent-object_linewise-none)
vmap ii <Plug>(indent-object_linewise-none)
omap ai <Plug>(indent-object_linewise-start)
vmap ai <Plug>(indent-object_linewise-start)
omap iI <Plug>(indent-object_linewise-end)
vmap iI <Plug>(indent-object_linewise-end)
omap aI <Plug>(indent-object_linewise-both)
vmap aI <Plug>(indent-object_linewise-both)
```
See docs for more details. I will add some note to README. Sorry for the late response.

**Comment by urxvtcd** [comment]
Added a note that there are no default mappings under "Usage" in README. Closing this issue. If you have any more questions feel free to reach out.
