### ISSUE TITLE
Error when press 'vii' in normal mode.

### ISSUE THREAD

**Issue by xiongwei0714** [urxvtcd/vim-indent-object#4]
I have maped ii according the doc.
But there is an error when press 'vii' in normal mode.
![image](https://github.com/urxvtcd/vim-indent-object/assets/15872815/78213ff4-a294-46cb-9802-b8d6f1fdc3e0)

From the error discription, it seems v:numbermax is not defined. I am using vim7.4 which may don't have this built-in varibale. Can you guide which version at least I should use and what is the meaning of 'numbermax'?

**Comment by urxvtcd** [comment]
Hi there, not sure what's the oldest version that works. I'll try to do some tests for that, and see if this can be fixed easily.

**Comment by urxvtcd** [comment]
I've pushed a workaround. Sorry it took so long. Feel free to report any further issues.
